---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04

provisioner:
    name: chef_zero

suites:
- name: default
  run_list:
    - "recipe[zabbix-server]"
  attributes:
